# Generated by Django 4.0.1 on 2022-02-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('paga', models.FloatField(null=True)),
                ('jornadas', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='Empresas')),
                ('fecha_creacion', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('total_empleos', models.BooleanField(default=True)),
                ('empleos', models.IntegerField(default=100)),
                ('video', models.FileField(upload_to='video')),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=100, null=True)),
                ('direccion', models.TextField()),
                ('paga', models.FloatField(null=True)),
                ('jornadas', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='Empresas')),
                ('email', models.EmailField(max_length=254)),
                ('video', models.FileField(upload_to='video')),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Especialidad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.FloatField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Empresas')),
                ('email', models.EmailField(max_length=254)),
                ('video', models.FileField(upload_to='video')),
                ('enlace', models.URLField()),
            ],
        ),
    ]
