# Generated by Django 4.0.1 on 2022-02-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastrabajos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleos',
            old_name='direccion',
            new_name='description',
        ),
    ]
