# Generated by Django 4.0.1 on 2022-02-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastrabajos', '0002_rename_direccion_empleos_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleos',
            options={'verbose_name': 'Empleos', 'verbose_name_plural': 'Empleos Disponibles'},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresas', 'verbose_name_plural': 'disponibles'},
        ),
        migrations.AlterModelOptions(
            name='perfiles',
            options={'verbose_name': 'perfiles', 'verbose_name_plural': 'usuarios '},
        ),
    ]
