# Generated by Django 4.0.1 on 2022-02-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastrabajos', '0003_alter_empleos_options_alter_empresas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleos',
            options={'verbose_name': 'Empleos', 'verbose_name_plural': 'Empleos disponibles'},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresas', 'verbose_name_plural': 'Empresas Disponibles'},
        ),
        migrations.AlterModelOptions(
            name='perfiles',
            options={'verbose_name': 'perfiles', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
