# Generated by Django 4.0.1 on 2022-03-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastrabajos', '0004_alter_empleos_options_alter_empresas_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='direccion',
            new_name='description',
        ),
    ]
