# Generated by Django 4.0.1 on 2022-03-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastrabajos', '0005_rename_direccion_empresas_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='paga',
        ),
    ]
