# Generated by Django 4.0.1 on 2022-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastrabajos', '0006_remove_empresas_paga'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.FloatField(null=True)),
                ('Mensaje', models.CharField(max_length=100)),
            ],
        ),
    ]
