# Generated by Django 4.0.1 on 2022-04-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastrabajos', '0007_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='image',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='video',
        ),
    ]
