# Generated by Django 4.0.1 on 2022-04-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastrabajos', '0008_remove_perfiles_image_remove_perfiles_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleos',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='empleos',
            name='video',
        ),
        migrations.AlterField(
            model_name='empleos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Empresas'),
        ),
    ]
