# Generated by Django 4.0.1 on 2022-04-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastrabajos', '0009_remove_empleos_enlace_remove_empleos_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleos',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
